#!/usr/bin/env bash
set -euo pipefail
# Nihongo Ride — macOS App Store build & upload.
# Usage: scripts/build-appstore.sh [--upload]
#
# Archives the Xcode app (generated by xcodegen from project.yml), then either
# stops at the archive (default) or exports+uploads to App Store Connect with
# the shared ASC API key (--upload).

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
cd "$ROOT"

# --- Build from an xattr-free copy when the source tree carries provenance ----
# macOS Sequoia stamps com.apple.provenance on files under ~/Documents; that
# xattr is STICKY (xattr -c / -d don't remove it) and makes codesign fail with
# "resource fork, Finder information, or similar detritus not allowed". So when
# it's present, mirror the working tree (incl. uncommitted changes) into a temp
# dir with rsync — rsync WITHOUT -X drops xattrs — and re-exec there. The
# NR_BUILD_COPY sentinel prevents re-looping; the copy also has no provenance so
# the inner run's check is false anyway. Skip entirely if the tree is clean
# (e.g. repo lives outside ~/Documents).
if [[ -z "${NR_BUILD_COPY:-}" ]] && xattr "$ROOT/project.yml" 2>/dev/null | grep -q com.apple.provenance; then
    WORK="$(mktemp -d "${TMPDIR:-/tmp}/nrbuild.XXXXXX")"
    echo "==> Source carries provenance xattrs (codesign-hostile); building from a clean copy:"
    echo "    $WORK"
    rsync -a --exclude .git --exclude build --exclude .build \
        --exclude '*.xcodeproj' --exclude .swiftpm "$ROOT/" "$WORK/"
    export NR_BUILD_COPY="$ROOT"
    exec "$WORK/scripts/build-appstore.sh" "$@"
fi

TEAM_ID="KHMK6Q3L3K"
API_KEY_ID="${ASC_KEY_ID:-DMMFP6XTXX}"
API_ISSUER="${ASC_ISSUER_ID:-c5671c11-49ec-47d9-bd38-5e3c1a249416}"
API_KEY_PATH="$HOME/.appstoreconnect/private_keys/AuthKey_${API_KEY_ID}.p8"
[[ -f "$API_KEY_PATH" ]] || API_KEY_PATH="$HOME/Library/Mobile Documents/com~apple~CloudDocs/Downloads/AuthKey_${API_KEY_ID}.p8"

UPLOAD=false
[[ "${1:-}" == "--upload" ]] && UPLOAD=true

BUILD_DIR="$ROOT/build/appstore"
ARCHIVE="$BUILD_DIR/NihongoRide.xcarchive"
EXPORT="$BUILD_DIR/export"
PROJECT="$ROOT/NihongoRide.xcodeproj"

echo "==> Regenerating Xcode project from project.yml"
xcodegen generate >/dev/null

rm -rf "$BUILD_DIR"; mkdir -p "$BUILD_DIR"

echo "==> [1/2] Archiving (Release, Apple Distribution, automatic signing)"
xcodebuild archive \
    -project "$PROJECT" \
    -scheme NihongoRide \
    -configuration Release \
    -archivePath "$ARCHIVE" \
    -destination "generic/platform=macOS" \
    -allowProvisioningUpdates \
    -authenticationKeyPath "$API_KEY_PATH" \
    -authenticationKeyID "$API_KEY_ID" \
    -authenticationKeyIssuerID "$API_ISSUER" \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    CODE_SIGN_STYLE=Automatic \
    -quiet
echo "    ✓ $ARCHIVE"

if [[ "$UPLOAD" != true ]]; then
    echo "==> [2/2] Skipping upload (pass --upload to export + upload to ASC)"
    echo "Done. Archive at $ARCHIVE"
    exit 0
fi

echo "==> [2/2] Exporting + uploading to App Store Connect"
cat > "$BUILD_DIR/ExportOptions.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store-connect</string>
    <key>teamID</key>
    <string>KHMK6Q3L3K</string>
    <key>destination</key>
    <string>upload</string>
    <key>signingStyle</key>
    <string>automatic</string>
    <key>uploadSymbols</key>
    <true/>
</dict>
</plist>
EOF

xcodebuild -exportArchive \
    -archivePath "$ARCHIVE" \
    -exportOptionsPlist "$BUILD_DIR/ExportOptions.plist" \
    -exportPath "$EXPORT" \
    -allowProvisioningUpdates \
    -authenticationKeyPath "$API_KEY_PATH" \
    -authenticationKeyID "$API_KEY_ID" \
    -authenticationKeyIssuerID "$API_ISSUER"

echo "    ✓ Uploaded. Apple will process the build (10-30 min) before it's attachable."
